import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/src/components/providers";
import { Toaster } from "react-hot-toast";
import PrelineScript from "@/src/components/PrelineScript";

export const metadata: Metadata = {
  title: {
    default: "Pusat Komputer Yogayakarta | PUSCOM",
    template: "%s | PUSCOM",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://use.typekit.net/ins2wgm.css" />
      </head>
      <body className="font-scandia">
        <PrelineScript />
        <Toaster position="top-right" reverseOrder={false} />
        <Providers>{children}</Providers>
        <script async src="https://kit.fontawesome.com/c7e6574aa8.js" crossOrigin="anonymous"></script>
      </body>
    </html>
  );
}
